leverxcourses/leverxcourses/urls.py
"""project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('authentication.urls', namespace='authentication')),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leverxcourses/main/urls.py
from django.conf.urls import url
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from . import views

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('courses/', views.CourseList.as_view()),
    path('courses/<int:pk>/', views.CourseDetail.as_view()),
    path('lectures/', views.LectureList.as_view()),
    path('lectures/<int:pk>/', views.LectureDetail.as_view()),
    path('tasks/', views.TaskList.as_view()),
    path('tasks/<int:pk>/', views.TaskDetail.as_view()),
    path('task_control/', views.TaskControlList.as_view()),
    path('task_control/<int:pk>/', views.TaskControlDetail.as_view()),
    path('task_comments/', views.TaskCommentsList.as_view()),
    path('task_comments/<int:pk>/', views.TaskCommentsDetail.as_view()),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

leverxcourses/main/models.py
from django.conf import settings
from django.db import models
from datetime import datetime

User = settings.AUTH_USER_MODEL

class CourseGroup(models.Model):
    name = models.CharField('Name', max_length=20)
    image = models.ImageField('Image', max_length=20)


class Course(models.Model):
    name = models.CharField('Name', max_length=20)
    date = models.DateField('Date start')
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/'


class Lecture(models.Model):
    theme = models.CharField('Theme', max_length=20)
    slides = models.FileField('Slides', upload_to=u'slides')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.theme

    def __unicode__(self):
        return u"file {0}".format(self.file.url)


class LectureTask(models.Model):
    name = models.CharField('Name', max_length=20)
    text = models.TextField('Text', max_length=250)
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/'


class TaskControl(models.Model):
    datetime = models.DateTimeField('DateTime', default=datetime.now())
    attachment = models.TextField('Homework')
    completed = models.BooleanField('Completed', default=False)
    checked = models.BooleanField('Checked', default=False)
    grade = models.SmallIntegerField('Grade', default=0)
    task = models.ForeignKey(LectureTask, on_delete=models.PROTECT)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.task

    def get_absolute_url(self):
        return f'/'


class TaskComments(models.Model):
    comment = models.TextField('Comment', max_length=250)
    datetime = models.DateTimeField('DateTime', default=datetime.now())
    taskcontrol = models.ForeignKey(TaskControl, on_delete=models.PROTECT)

    def __str__(self):
        return self.datetime

    def get_absolute_url(self):
        return f'/'

leverxcourses/main/forms.py
from .models import Course, Lecture, LectureTask, CourseGroup, TaskControl
from django.forms import ModelForm, TextInput, DateInput, FileInput, Select, Textarea, CheckboxSelectMultiple, \
    SelectMultiple, ImageField, FileField, NullBooleanSelect


class CoursesForm(ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'date']

        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Сourse name'
            }),
            "date": DateInput(attrs={
                'class': 'form-control',
                'placeholder': 'Start date'
            }),
        }


class LectureForm(ModelForm):
    class Meta:
        model = Lecture
        fields = ['theme', 'slides', 'course']

        widgets = {
            "theme": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Lecture name'
            }),
            "slides": FileInput(attrs={
                'type': 'file'
            }),
            "course": Select(attrs={
                'class': 'form-control',
                'placeholder': 'Course'
            })
        }


class TaskForm(ModelForm):
    class Meta:
        model = LectureTask
        fields = ['name', 'text', 'lecture']

        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Task name'
            }),
            "text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Description'
            }),
            "lecture": Select(attrs={
                'class': 'form-control',
                'placeholder': 'Course'
            }),
        }


class AddUserForm(ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'users', 'date']

        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Task name'
            }),
            "text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Description'
            }),
            "date": DateInput(attrs={
                'class': 'form-control',
                'placeholder': 'Start date'
            }),
            "users": SelectMultiple()
        }


class TaskControlForm(ModelForm):
    class Meta:
        model = TaskControl
        fields = ['datetime', 'attachment', 'completed', 'task']

        widgets = {
            "datetime": DateInput(attrs={
                'class': 'form-control',
                'placeholder': 'DateTime'
            }),
            "attachment": TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Reference"
            }),
            "completed": NullBooleanSelect(attrs={
                'class': 'form-control',
                'placeholder': 'Completed'
            }),
            "task": Select(attrs={
                'class': 'form-control',
                'placeholder': 'Completed'
            })
        }

leverxcourses/main/views.py
from django.contrib.auth import get_user_model
from django.db import DatabaseError
from django.http import Http404
from rest_framework import generics, mixins, status
from rest_framework.parsers import MultiPartParser
from rest_framework.permissions import DjangoModelPermissions, IsAuthenticated, AllowAny
from rest_framework.response import Response

from . import serializers
from .models import Course, Lecture, LectureTask, TaskControl, TaskComments
from .permissions import LecturerOrGetPermissions
import logging

logger = logging.getLogger('django')


#################################COURSES#################################
class CourseList(mixins.ListModelMixin,
                 mixins.CreateModelMixin,
                 generics.GenericAPIView):
    """
    API endpoint that allows get list of user's current courses
    and create new courses
    """
    serializer_class = serializers.CourseSerializer
    permission_classes = [LecturerOrGetPermissions]

    def get_queryset(self):
        return Course.objects.filter(users=self.request.user)

    def get(self, request, *args, **kwargs):
        logger.info('Get Courses List for user')
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logger.info('Add new Course for user')
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        new_course = serializer.save()
        new_course.users.add(self.request.user)
        headers = self.get_success_headers(serializer.data)
        result = Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
        return result


class CourseDetail(mixins.RetrieveModelMixin,
                   mixins.UpdateModelMixin,
                   mixins.DestroyModelMixin,
                   generics.GenericAPIView):
    """
    API endpoint that allows update and delete courses
    """
    serializer_class = serializers.CourseSerializer
    permission_classes = [LecturerOrGetPermissions]

    def get_queryset(self):
        return Course.objects.filter(users=self.request.user)

    def get(self, request, *args, **kwargs):
        logger.info('Get Course')
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        logger.info('Update Course')
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        logger.info('Delete Course')
        return self.destroy(request, *args, **kwargs)


#################################LECTURES#################################
class LectureList(mixins.ListModelMixin,
                  mixins.CreateModelMixin,
                  generics.GenericAPIView):
    """
    API endpoint that allows get list of user's current lectures
    and create new lectures
    """
    serializer_class = serializers.LectureSerializer
    permission_classes = [LecturerOrGetPermissions]

    def get_queryset(self):
        return Lecture.objects.filter(course__users=self.request.user)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class LectureDetail(mixins.RetrieveModelMixin,
                    mixins.UpdateModelMixin,
                    mixins.DestroyModelMixin,
                    generics.GenericAPIView):
    serializer_class = serializers.LectureSerializer
    permission_classes = [LecturerOrGetPermissions]
    parser_classes = (MultiPartParser,)

    def get_queryset(self):
        return Lecture.objects.filter(course__users=self.request.user)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


#################################TASKS#################################

class TaskList(mixins.ListModelMixin,
               mixins.CreateModelMixin,
               generics.GenericAPIView):
    """
    API endpoint that allows get list of user's current tasks
    and create new tasks
    """
    serializer_class = serializers.TaskSerializer
    permission_classes = [LecturerOrGetPermissions]

    def get_queryset(self):
        return LectureTask.objects.filter(lecture__course__users=self.request.user)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class TaskDetail(mixins.RetrieveModelMixin,
                 mixins.UpdateModelMixin,
                 mixins.DestroyModelMixin,
                 generics.GenericAPIView):
    """
    API endpoint that allows get, update, delete tasks
    """
    serializer_class = serializers.TaskSerializer
    permission_classes = [LecturerOrGetPermissions]

    def get_queryset(self):
        return LectureTask.objects.filter(lecture__course__users=self.request.user)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


##############################TaskControl#################################
class TaskControlList(mixins.ListModelMixin,
                      mixins.CreateModelMixin,
                      generics.GenericAPIView):
    """
    API endpoint that allows get list of user's current home tasks
    and create new home tasks
    """
    serializer_class = serializers.TaskControlSerializer
    permission_classes = [AllowAny, ]

    def get_queryset(self):
        return TaskControl.objects.filter(task__lecture__course__users=self.request.user)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class TaskControlDetail(mixins.RetrieveModelMixin,
                        mixins.UpdateModelMixin,
                        mixins.DestroyModelMixin,
                        generics.GenericAPIView):
    """
    API endpoint that allows get, update, delete home tasks
    """
    serializer_class = serializers.TaskSerializer
    permission_classes = [AllowAny, ]

    def get_queryset(self):
        return TaskControl.objects.filter(task__lecture__course__users=self.request.user)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


##############################TaskComments#################################
class TaskCommentsList(mixins.ListModelMixin,
                       mixins.CreateModelMixin,
                       generics.GenericAPIView):
    """
    API endpoint that allows get list of user's comments in home tasks
    and create new comments
    """
    serializer_class = serializers.TaskControlSerializer
    permission_classes = [AllowAny]

    def get_queryset(self):
        return TaskComments.objects.filter(taskcontrol__task__lecture__course__users=self.request.user)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class TaskCommentsDetail(mixins.RetrieveModelMixin,
                         mixins.UpdateModelMixin,
                         mixins.DestroyModelMixin,
                         generics.GenericAPIView):
    """
    API endpoint that allows get, update, delete comments in home tasks
    """
    serializer_class = serializers.TaskSerializer
    permission_classes = [AllowAny]

    def get_queryset(self):
        return TaskComments.objects.filter(task__lecture__course__users=self.request.user)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

leverxcourses/main/templates/main/add_comment.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Add comment{% endblock %}

{% block content %}
<div class="main-list">
    <form method="post">
        <h1>Add comment</h1>
        {% csrf_token %}
        {{ form.datetime}}<br>
        Comment {{ form.comment}}<br>
        <span>{{ error }}</span><br>
        <button class="btn btn-success" type="submit">Add comment</button>
    </form>
</div>
{% endblock %}

leverxcourses/main/templates/main/comments_taskcontrol.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}
<div class="main-list">
    <table class="table" style="width: 65%">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Comment</th>
        </tr>
        {% if task_comments %}
        {% for el in task_comments %}
        <tr>
            <td>{{el.datetime}}</td>
            <td>Comment {{el.comment}}</td>
        </tr>
        {% endfor %}
        {% endif %}
    </table>
    <a href="{% url 'add_comment' taskcontrol %}">
        <button class="btn btn-info">Add Comment</button>
    </a>
</div>
{% endblock %}

leverxcourses/main/templates/main/course_details.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block aside %}
    <img src="{% static 'main/img/img_LeverX.png' %}" alt="Logo">
    <span class="Logo">Lectures</span>
{% endblock %}

{% block menu %}
    <span class="Logo">{{ course.name }}</span>
        <ul>
            <a href="{% url 'lectures' course.id %}"><li><i class="fas fa-chalkboard-teacher"></i> Lectures </li></a>
<!--            <a href="{% url 'tasks' course.id %}"><li><i class="fas fa-tasks"></i> Tasks </li></a>-->
            <a href="{% url 'course_users' course.id %}"><li><i class="fas fa-book-reader"></i> Users </li></a>
        </ul>
<!--    <a href="{% url 'home' %}"><button class="btn btn-info btn-pos">Home</button></a>-->

{% endblock %}

{% block content %}

{% endblock %}

leverxcourses/main/templates/main/create.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Add Course{% endblock %}

{% block content %}
    <div class="features">
        <h1 style="margin-left:32%">Add Course</h1>
        <form method="post">
            <input type="text" placeholder="Name of course" class="form-control"><br>
            <input type="text" placeholder="Course group" class="form-control"><br>
            <button class="btn btn-success" type="submit">Add Course</button>
        </form>
    </div>
{% endblock %}

leverxcourses/main/templates/main/create_lecture.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Add Course{% endblock %}

{% block content %}
<div class="features">
    <form method="post" enctype="multipart/form-data">
        <h1>Add Lecture</h1>
        {% csrf_token %}
        {{ form.name}}<br>
        {{ form.slides}}<br>
        {{ form.course}}<br>
        <span>{{ error }}</span><br>
        <button class="btn btn-success" type="submit">Add Lecture</button>
    </form>
</div>
{% endblock %}

leverxcourses/main/templates/main/delete_course.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Delete course{% endblock %}

{% block content %}
<div class="features">
    <form method="post">
        <h1>Are you sure?</h1>
        {% csrf_token %}
        <span>{{ error }}</span><br>
        <button class="btn btn-success" type="submit">Delete course</button>
    </form>
</div>
{% endblock %}

leverxcourses/main/templates/main/delete_lecture.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Delete course{% endblock %}

{% block content %}
<div class="features">
    <form method="post">
        <h1>Are you sure?</h1>
        {% csrf_token %}
        <span>{{ error }}</span><br>
        <button class="btn btn-success" type="submit">Delete lecture</button>
    </form>
</div>
{% endblock %}

leverxcourses/main/templates/main/delete_task.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Delete course{% endblock %}

{% block content %}
<div class="features">
    <form method="post">
        <h1>Are you sure?</h1>
        {% csrf_token %}
        <span>{{ error }}</span><br>
        <button class="btn btn-success" type="submit">Delete task</button>
    </form>
</div>
{% endblock %}

leverxcourses/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
<div class="main-list">
    <ul class="no-bullets">
        {% if courses %}
        {% for el in courses %}
        <li>
            <div class="main-block">
                <img width='70px' height="70px" style="display: inline-block; position:relative; top:-15px;"
                     src="{% static 'main/img/python.jpg' %}">
                <div style="display: inline-block; position:relative; left:20px; top:5px;">
                    <a href="{% url 'course_details' el.id %}" class="main-name"><h3>{{el.name}}</h3></a>
                    <div>
                        <span>{{el.date}}</span>
                        <!--                            {% for le in el.lecturers %}-->
                        <!--                            <span>{{ le }} *</span>-->
                        <!--                            {% endfor%}-->
                    </div>
                </div>
                {% if perms.main.add_course %}
                    <div style="margin: 5px; float: right; position:relative; top:20px;">
                        {% if perms.main.delete_course %}
                        <a href="{% url 'delete' el.id %}" class="btn btn-warning">Delete course</a>
                        {% endif %}

                        {% if perms.main.change_course %}
                        <a href="{% url 'update' el.id %}" class="btn btn-info">Update course</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </li>
        {% endfor %}
        {% if perms.main.add_course %}
        <li>
            <div class="add-block">
                <a href="{% url 'create' %}">
                    <button class="btn btn-info"><i class="fas fa-plus-circle"></i>Add course</button>
                </a>
            </div>
        </li>
        {% endif %}
        {% else %}
        <p> No records </p>
        {% endif %}
    </ul>
</div>
{% endblock %}

leverxcourses/main/templates/main/layout.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>{% block title %}{% endblock%}</title>
</head>
<body>
<aside>
    <a href="{% url 'home' %}"><img style="width: 45%; display: inline-block"
                                    src="{% static 'main/img/img_LeverX.png' %}" alt="Logo">
        <p style="width: 40%; display: inline-block" class="main-logo">Courses</p></a>

    <a style="position: absolute; height: 10px;  bottom: 100px; left: 5%" href="{% url 'logout' %}">
        <button class="btn btn-info">Log Out</button>
    </a>

    {% block menu %}
    {% endblock %}
</aside>

<main>
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

leverxcourses/main/templates/main/lectures.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}{{ el.name }}{% endblock %}

{% block content %}
<div class="main-list">
    <h1>Lectures</h1>
    <ul class="no-bullets">
        {% if lectures %}
        {% for el in lectures %}
        <li>
            <div class="main-block">
                <button style="margin: 5px; position:relative; top:10px;"
                        type="button" class="btn btn-info" data-toggle="collapse" data-target="#{{el.id}}">{{el.name}}
                </button>
                <div id="{{el.id}}" class="collapse" style="padding : 3em">
                    <a href="{{el.slides}}" download="{{el.slides}}">{{ el.slides }}</a>
                </div>
                <div style="margin: 5px; float: right; position:relative; top:10px;">
                    <a href="{% url 'tasks' el.id %}" class="btn btn-info">Tasks</a>
                    {% if perms.main.delete_lecture %}
                        <a href="{% url 'delete_lecture' el.id %}" class="btn btn-warning">Delete lecture</a>
                    {% endif%}
                    {% if perms.main.change_lecture %}
                        <a href="{% url 'update_lecture' el.id %}" class="btn btn-info">Update lecture</a>
                    {% endif%}
                </div>
            </div>
        </li>
        {% endfor %}
        {% else %}
        <p> No records </p>
        {% endif %}
        {% if perms.main.add_lecture %}
            <li>
                <div class="add-block">
                    <a href="{% url 'create_lecture' course_id %}">
                        <button class="btn btn-info"><i class="fas fa-plus-circle"></i>Add lecture</button>
                    </a>
                </div>
            </li>
       {% endif%}
    </ul>
    {% endblock %}

leverxcourses/main/templates/main/taskcontrol.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block menu %}
<span class="Logo">{{course.name}}</span>
{% endblock %}

{% block content %}
<div class="main-list">
    <p>{{ Fro }}</p>
    <table class="table" style="width: 65%">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Attachment</th>
            <th scope="col">Completed</th>
            <th scope="col">Grade</th>
            {% if perms.main.delete_taskcontrol %}
            <th scope="col" style="width: 60px">Delete</th>
            {% endif %}
            {% if perms.main.update_taskcontrol %}
            <th scope="col" style="width: 60px">Update</th>
            {% endif %}
        </tr>
        {% if taskcontrols %}
        {% for el in taskcontrols %}
        <tr>
            <td>{{el.datetime}}</td>
            <td>Attachment {{el.attachment}}</td>
            <td>Completed {{el.completed}}</td>
            <td><a href="{% url 'comments_taskcontrol' el.id %}">Grade {{el.grade}}</a></td>
            {% if perms.main.delete_taskcontrol %}
                <td><a href="{% url 'delete_taskcontrol' el.id %}">Delete</a></td>
            {% endif %}
                {% if perms.main.update_taskcontrol %}
            <td><a href="{% url 'update_taskcontrol' el.id %}">Update</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        {% endif %}
    </table>
    <a href="{% url 'add_taskcontrol' task_id%}">
        <button class="btn btn-info">Add Home Task</button>
    </a>
</div>
{% endblock %}

leverxcourses/main/templates/main/test_include.html
<p>Привет из test_include!</p>

leverxcourses/main/templates/main/update_taskcontrol.html
{% extends 'main/layout.html' %}

{% load static %}

{% block title %}Update {% endblock %}

{% block content %}
<div class="main-list">
    <form method="post">
        <h1>Update homework</h1>
        {% csrf_token %}
        {{ form.attachment}}<br>
        {{form.checked }}<br>
        {{ form.grade }}<br>
        {{form.comments}}<br>
        <span>{{ error }}</span><br>
        <button class="btn btn-success" type="submit">Update homework</button>
    </form>
</div>
{% endblock %}